services:
  booth:
    command: python manage.py runserver 0.0.0.0:5656
    volumes:
      - ./src:/app
    env_file:
      - .env.dev
    ports:
      - "5656:5656"
  
  db:
    restart: unless-stopped
    volumes:
      - ./booth_base:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env.dev
    environment:
      - POSTGRES_USER: ${DB_USER}
      - POSTGRES_PASSWORD: ${DB_PASSWORD}
      - POSTGRES_DB: ${DB_NAME}