services:

# Creates a new service called booth with Django application
  booth:
    image: booth
    container_name: booth
    command: sh -c "gunicorn app.wsgi:application -b 0.0.0.0:5656"
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/app
      - /src/static:/static
    expose:
      - 5656:5656
    depends_on:
      - postgres

# Creates a new service called postgres with Postgres database
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

# Creates a new service called nginx with Nginx web server 
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 5656:5656
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./src:/app
    depends_on:
      - booth

    